# Numpy

In [2]:
import numpy as np

# Numpy Array

In [3]:
benimListem = [20, 30, 40]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([20, 30, 40])

In [7]:
type(np.array(benimListem))

numpy.ndarray

In [8]:
matrix_listesi = [[10, 20, 30], [20, 30 ,40], [30, 40, 50]]

In [10]:
matrix_listesi[2][1]

40

In [11]:
np.array(matrix_listesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# Arange

In [12]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Zeros and Ones

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((9, 9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

In [28]:
np.linspace(0, 20, 7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [29]:
np.linspace(0, 10, 41)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,
        4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,
        6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,
        9.  ,  9.25,  9.5 ,  9.75, 10.  ])

In [30]:
np.linspace(0, 100, 100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

# Eye

In [32]:
np.eye(3)     #identity matrix oluşturur

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random

In [34]:
np.random.randn(3)

array([0.20059882, 0.07204227, 1.76414753])

In [35]:
np.random.randn(3, 3)

array([[-0.56872116, -0.09275834, -0.03124741],
       [ 1.40810954, -0.36787087,  1.12864104],
       [-0.42999609, -2.36997206, -0.03572384]])

In [39]:

for i in range(5):
    print(np.random.randint(1, 10))

8
1
9
8
2


In [42]:
np.random.randint(1, 300, 5)      #1'den 300'e kadar rastgele 5 sayı döndür

array([195,  76, 223, 292, 110])

In [43]:
random_numbers = np.random.randint(1, 300, 5)

In [44]:
random_numbers

array([266,   1, 220, 294,  34])

In [45]:
numpy_array = np.arange(30)

In [46]:
numpy_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# Numpy Array Methods

In [47]:
numpy_array.reshape(5, 6)     #daima dizi boyuutu kadar row column degerleri verilmeli

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
print(numpy_array.max())

29


In [54]:
print(random_numbers.max())

294


In [55]:
print(numpy_array.min())

0


In [56]:
print(random_numbers.min())

1


In [58]:
print(numpy_array.argmax())    #max degerin kacıncı indexte oldugunu verir

29


In [61]:
print(random_numbers.argmin()) #min degerin kacıncı indexte oldugunu verir

1


In [62]:
numpy_array.shape

(30,)

In [63]:
numpy_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
reshape_array = numpy_array.reshape(3,10)

In [66]:
reshape_array.shape   #arrayin şu anda oldugu şekil yapısını verir

(3, 10)