In [1]:
import numpy as np

In [2]:
myArray = np.arange(0, 15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
print(myArray[5])

5


In [7]:
myArray[3:5]

array([3, 4])

In [8]:
myArray[3:8]

array([3, 4, 5, 6, 7])

In [11]:
myArray[3:8] = -5    #3 ve 8inci index arası -5 değerine eşitlendi

In [12]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
secondArray = np.arange(0, 24)

In [14]:
secondArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingArray = secondArray[4:9]

In [16]:
slicingArray

array([4, 5, 6, 7, 8])

In [19]:
slicingArray[:] = 700

In [20]:
slicingArray

array([700, 700, 700, 700, 700])

In [23]:
secondArray    #oluşturdugumuz ikinci dizide yaptıgım değişiklikler, ikinci diziye kaynak oluşturduğum dizinin içinde de değişiklik yapar

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [39]:
exampleArray = np.arange(0, 15)

In [40]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
exampleArrayCopy = exampleArray.copy()

In [42]:
exampleArrayCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
exampleArrayCopySlicing = exampleArrayCopy[3:6]
exampleArrayCopySlicing[:] = 232
print(exampleArrayCopySlicing)
print(exampleArrayCopy)
print(exampleArray)

[232 232 232]
[  0   1   2 232 232 232   6   7   8   9  10  11  12  13  14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Matrix

In [44]:
myList = [[10, 20, 30], [20, 30, 40], [40, 50 ,60]]

In [45]:
exampleMatrix = np.array(myList)

In [46]:
exampleMatrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [49]:
print(exampleMatrix[0][2])      #exampleMatrix[raw][column]

30


In [51]:
print(exampleMatrix[0, 2])

30


In [54]:
exampleMatrix[0: ,1:]

array([[20, 30],
       [30, 40],
       [50, 60]])

In [55]:
exampleMatrix[0: ,1]

array([20, 30, 50])

In [56]:
exampleMatrix[0: ,2]

array([30, 40, 60])

In [57]:
newList = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]

In [58]:
newMatrix = np.array(newList)

In [59]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
newMatrix[[0, 2, 4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [65]:
newMatrix[[4, 2, 0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [66]:
newMatrix[[4, 2, 0], [3]]       #4ncü 2nci 0nci indexli satırların 3 indexli sütun degerlerini getirdi

array([23, 13,  3])

# Operations

In [75]:
newArray = np.random.randint(3, 3000, 20)

In [76]:
newArray

array([ 510, 2266,  245, 2420, 2843, 2553, 2050, 2740,  229, 2559, 2334,
       2013, 2033, 2858,  965, 2520, 1253,  895, 1883, 2837])

In [77]:
newArray > 24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [78]:
newArray > 1500

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False, False,
        True,  True])

In [81]:
resultArray = newArray > 1500

In [82]:
resultArray

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False, False,
        True,  True])

In [84]:
newArray[resultArray]

array([2266, 2420, 2843, 2553, 2050, 2740, 2559, 2334, 2013, 2033, 2858,
       2520, 1883, 2837])

In [85]:
newArray[newArray <2323]

array([ 510, 2266,  245, 2050,  229, 2013, 2033,  965, 1253,  895, 1883])

In [86]:
lastArray = np.arange(0, 24)

In [87]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [88]:
lastArray * lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [89]:
lastArray - lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [92]:
lastArray / lastArray   #0 degerinin hatasını verir ama geri kalanı calıştırır

/var/folders/h5/807f4bmn69100fg26mvxsydh0000gn/T/ipykernel_62524/770655647.py:1: RuntimeWarning: invalid value encountered in divide
  lastArray / lastArray   #0 degerinin hatasını verir ama geri kalanı calıştırır


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [95]:
print(np.max(newArray))

2858


In [96]:
print(np.min(newArray))

229
